services:
  db:
    image: postgres:15-alpine
    container_name: mercabot_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mercabot
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: mercabot_web
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=password123
      - DB_NAME=mercabot
    volumes:
      - static_images:/app/static/img

volumes:
  postgres_data:
  static_images: